
logging:
  level:
    ROOT: DEBUG
    com.jaiser: DEBUG

server:
  port: 9891

#mysql
spring:
  application:
    name: wechat-rob
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

